### ISSUE TITLE
System.IO.DirectoryNotFoundException when running the sample

### ISSUE THREAD

**Issue by kyberias** [OfficeDev/microsoft-teams-sample-outgoing-webhook#3]
After compiling the sample with VS 2017 15.9.16 and starting it I get the following error:

Could not find a part of the path 'D:\Projects\microsoft-teams-sample-outgoing-webhook\WebhookSampleBot\bin\roslyn\csc.exe'.

**Comment by kirbby** [comment]
https://stackoverflow.com/a/34391473/5845898
This worked for me. Just run the command in the NuGet console.
